version: '4'
services:
  mysql:
    image : mysql:8.0.38
    container_name: inventory_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 6969
    ports:
      - "3316:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
